# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 08:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='grumblr_pics')),
                ('textpost', models.CharField(max_length=400)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='/media/user_pics/user_default.png', upload_to='user_pics')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('self_description', models.CharField(blank=True, max_length=400)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='socialnetwork.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='grumblrcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='grumblrcomment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='grumblrpost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='grumblrpost',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='grumblrprofile',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='grumblrprofile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='grumblrprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GrumblrComment',
        ),
        migrations.DeleteModel(
            name='GrumblrPost',
        ),
        migrations.DeleteModel(
            name='GrumblrProfile',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_profile', to='socialnetwork.Profile'),
        ),
    ]
